config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :payments, except: [:new]
  resources :enrollments
  resources :students
  resources :institutions
  #  Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/institution.rb
class Institution < ApplicationRecord
    has_many :enrollments, dependent: :destroy

    validates_presence_of :name
    validates :name, uniqueness: { message: 'is already in use' }
    validates :cnpj, uniqueness: { message: 'is already in use' }
    validates :cnpj, numericality: { only_integer: true, message: 'must be a number' }
    validates :institution_type, inclusion: { in: %w[university school nursey],
                                              message: 'must be university, school or nursey' }
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: %i[show edit update destroy]

  # GET /institutions or /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1 or /institutions/1.json
  def show; end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit; end

  # POST /institutions or /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to institution_url(@institution), notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1 or /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to institution_url(@institution), notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1 or /institutions/1.json
  def destroy
    @institution.destroy

    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_institution
    @institution = Institution.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def institution_params
    params.require(:institution).permit(:name, :cnpj, :institution_type)
  end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= form_with(model: institution) do |form| %>
  <% if institution.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
        <% institution.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cnpj, style: "display: block" %>
    <%= form.text_field :cnpj %>
  </div>

  <div>
    <%= form.label :institution_type, style: "display: block" %>
    <%= form.select :institution_type, [["University", "university"], ["School", "scholl"], ["Nursey", "nursey"]]%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/institutions/_institution.html.erb
<div id="<%= dom_id institution %>">
  <p>
    <strong>Name:</strong>
    <%= institution.name %>
  </p>

  <p>
    <strong>Cnpj:</strong>
    <%= institution.cnpj %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= institution.institution_type %>
  </p>

</div>

app/views/institutions/edit.html.erb
<h1>Editing institution</h1>

<%= render "form", institution: @institution %>

<br>

<div>
  <%= link_to "Show this institution", @institution %> |
  <%= link_to "Back to institutions", institutions_path %>
</div>

app/views/institutions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Institutions</h1>

<div id="institutions">
  <table class="table">
    <tr>
      <th>Name</th>
      <th>CNPJ</th>
      <th>Type</th>
      <th>Actions</th>
    </tr>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%=institution.name %></td>
        <td><%=institution.cnpj %></td>
        <td><%=institution.institution_type.capitalize %></td>
        <td>
          <%= button_to "Edit", edit_institution_path(institution), method: :get, class: 'btn btn-sm btn-info' %>
          <%= button_to "Delete", institution, method: :delete, class: 'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to "New institution", new_institution_path %>

app/views/institutions/new.html.erb
<h1>New institution</h1>

<%= render "form", institution: @institution %>

<br>

<div>
  <%= link_to "Back to institutions", institutions_path %>
</div>

app/views/institutions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @institution %>

<div>
  <%= link_to "Edit this institution", edit_institution_path(@institution) %> |
  <%= link_to "Back to institutions", institutions_path %>

  <%= button_to "Destroy this institution", @institution, method: :delete %>
</div>