config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :payments, except: [:new]
  resources :enrollments
  resources :students
  resources :institutions
  #  Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :enrollments, dependent: :destroy
    validates :name, uniqueness: { message: 'already exists!' }
    validates :cpf, uniqueness: { message: 'already exists!' }
    validates_presence_of :name, :cpf, :gender, :payment_type
    validates :cpf, numericality: { only_integer: true, message: 'must be a number' }
    validates :gender, inclusion: { in: %w[m f], message: "must be 'f' (female) or 'm' (male)" }
    validates :payment_type, inclusion: { in: %w[boleto card], message: "must be 'boleto' or 'card'" }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update destroy]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show; end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit; end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:name, :cpf, :birth_date, :phone, :gender, :payment_type)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :birth_date, style: "display: block" %>
    <%= form.date_field :birth_date %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.number_field :phone %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.select :gender, [["Female", 'f'], ["Male", 'm']]%>
  </div>
  
  </br>
  <div>
    <%= form.label :payment_type, style: "display: block" %>
    <%= form.select :payment_type, [["Card", "card"], ["Brazil Boleto", "boleto"]]%>
  </div>
  
  </br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= student.cpf %>
  </p>

  <p>
    <strong>Birth date:</strong>
    <%= student.birth_date %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= student.phone %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= student.gender %>
  </p>

  <p>
    <strong>Payment type:</strong>
    <%= student.payment_type %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <table class="table">
    <tr>
      <th>Name</th>
      <th>CPF</th>
      <th>Birth date</th>
      <th>Phone</th>
      <th>Gender</th>
      <th>Payment Type</th>
      <th>Actions</th>
    </tr>
    <% @students.each do |student| %>
      <tr>
        <td><%=student.name %></td>
        <td><%=student.cpf %></td>
        <td><%=student.birth_date %></td>
        <td><%=student.phone %></td>
        <td><%=student.gender == "f" ? "Female" : "Male"  %></td>
        <td><%=student.payment_type.capitalize %></td>
        <td>
          <%= button_to "Edit", edit_student_path(student), method: :get, class: 'btn btn-sm btn-info' %>
          <%= button_to "Delete", student, method: :delete, class: 'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>