config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :payments, except: [:new]
  resources :enrollments
  resources :students
  resources :institutions
  #  Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid" style="">
    <%= link_to 'Billinho Project', root_path,class:"navbar-brand"%>
   <!-- <div class="mx-auto" style="width: 200px;">--> <!-- faz um espaço estranho-->

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"> 
          <%= link_to 'Institutions',institutions_path, class:"nav-link active" %>
          <li class="nav-item">
        <%= link_to 'Students', students_path, class:"nav-link active" %>
         <<!-- <a class="nav-link active" aria-current="page" href="#">Home</a>-->
        </li>
        <li class="nav-item">
        <%= link_to 'Enrollments', enrollments_path, class:"nav-link active" %>
        <li class="nav-item">
       <%= link_to 'Payments', payments_path, class:"nav-link active" %>
        <li class="nav-item">
        </li>
       <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Update the Information
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/institutions/new"> Create Institution</a></li>
            <li><a class="dropdown-item" href="/students/new">Create Student</a></li>
            <li><a class="dropdown-item" href="/enrollments/new">Create Enrollment</a></li>
          </ul>
        </li>-->
        <!--<li class="nav-item">-->
         <!-- <a class="nav-link disabled">Disabled</a>-->
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<center>
    <br><br><br><br>
    <h1>Welcome to Billinho</h1>
    <p>A project by Hevelyn and Yuri</p>

    <br><br>
    The Billinho project aims to simulate an API for managing the monthly fees paid by students to the educational institution they study.
</center>