config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :payments, except: [:new]
  resources :enrollments
  resources :students
  resources :institutions
  #  Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
    belongs_to :institution
    belongs_to :student
    has_many :payment, dependent: :delete_all
    validates_presence_of :course_name, :institution_id, :student_id, :course_price, :number_payments, :due_day
    validates :course_price, numericality: { greater_than: 0, message: 'must be greater than 0' }
    validates :number_payments, numericality: { in: 1..120 }
    validates :due_day, numericality: { in: 1..31 }

    after_create :create_payments
    after_update :update_payments

    def enrollment_info
        "Enroll id: #{id} - #{student.name} - #{course_name}"
    end

    def create_payments
        payment_value = course_price.to_f / number_payments
        payment_due_date = get_due_date(Date.today, due_day)

        (1..number_payments).each do
            Payment.create(payment_params(payment_value, payment_due_date, id))
            payment_due_date = get_due_date(payment_due_date.next_month, due_day)
        end
    end

    def payment_params(payment_value, payment_due_date, enroll_id)
        {
            value: payment_value,
            due_date: payment_due_date,
            status: 'open',
            enrollment_id: enroll_id
        }
    end

    def get_due_date(current_date, due_day)
        payment_due_date = \
          if Date.valid_date?(current_date.year, current_date.month, due_day)
              Date.new(current_date.year, current_date.mon, due_day)
          else
              current_date.end_of_month
          end
        payment_due_date = get_due_date(payment_due_date.next_month, due_day) if payment_due_date <= Date.today
        payment_due_date
    end

    def update_payments
        return unless previous_changes.key?('due_day')

        payments = Payment.where(enrollment_id: id, status: 'open').all
        payments.each do |payment|
            payment.due_date = get_due_date(payment.due_date, due_day)
            payment.save
        end
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[show edit update destroy]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show; end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit; end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollment_url(@enrollment), notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollments_params_can_updated)
        format.html { redirect_to enrollment_url(@enrollment), notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_enrollment
    @enrollment = Enrollment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def enrollment_params
    params.require(:enrollment)
          .permit(:student_id, :institution_id, :course_price, :number_payments, :due_day, :course_name)
  end

  def enrollments_params_can_updated
    params.require(:enrollment).permit(:due_day, :course_name)
  end

  def prof
    @student = Student.find(enrollment_params[:student_id])
    @institution = Institution.find(enrollment_params[:institution_id])
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  <p>
  <strong>Student:</strong>
  <%= enrollment.student.name %>
  </p>

  <p>
  <strong>Institution:</strong>
  <%= enrollment.institution.name %>
  </p>

  <p>
    <strong>Course price:</strong>
    <%= enrollment.course_price %>
  </p>

  <p>
    <strong>Number payments:</strong>
    <%= enrollment.number_payments %>
  </p>

  <p>
    <strong>Due day:</strong>
    <%= enrollment.due_day %>
  </p>

  <p>
    <strong>Course name:</strong>
    <%= enrollment.course_name %>
  </p>

</div>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= form_with(model: @enrollment) do |form| %>
  <% if @enrollment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% @enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :due_day, style: "display: block" %>
    <%= form.number_field :due_day %>
  </div>

  <div>
    <%= form.label :course_name, style: "display: block" %>
    <%= form.text_field :course_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Show this enrollment", @enrollment %> |
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enrollments</h1>

<div id="enrollments">
  <table class="table">
    <tr>
      <th>Student</th>
      <th>Institution</th>
      <th>Course name</th>
      <th>Course price</th>
      <th>Number payments</th>
      <th>Due day</th>
      <th>Actions</th>
    </tr>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%=enrollment.student.name %></td>
        <td><%=enrollment.institution.name %></td>
        <td><%=enrollment.course_name %></td>
        <td><%=enrollment.course_price %></td>
        <td><%=enrollment.number_payments %></td>
        <td><%=enrollment.due_day %></td>
        <td>
          <%= button_to "Edit", edit_enrollment_path(enrollment), method: :get, class: 'btn btn-sm btn-info' %> 
          <%= button_to "Delete", enrollment, method: :delete, class: 'btn btn-sm btn-danger'  %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to "New enrollment", new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= form_with(model: @enrollment) do |form| %>
  <% if @enrollment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% @enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= collection_select(:enrollment, :student_id, Student.all, :id, :name) %>
  </div>

  <div>
    <%= form.label :institution_id, style: "display: block" %>
    <%= collection_select(:enrollment, :institution_id, Institution.all, :id, :name) %>
  </div>

  <div>
    <%= form.label :course_price, style: "display: block" %>
    <%= form.text_field :course_price %>
  </div>

  <div>
    <%= form.label :number_payments, style: "display: block" %>
    <%= form.number_field :number_payments %>
  </div>

  <div>
    <%= form.label :due_day, style: "display: block" %>
    <%= form.number_field :due_day %>
  </div>

  <div>
    <%= form.label :course_name, style: "display: block" %>
    <%= form.text_field :course_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enrollment %>

<div>
  <%= link_to "Edit this enrollment", edit_enrollment_path(@enrollment) %> |
  <%= link_to "Back to enrollments", enrollments_path %>

  <%= button_to "Destroy this enrollment", @enrollment, method: :delete %>
</div>